# Generated by Django 4.2.29 on 2026-04-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_venda_produtos_venda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
    ]
